export const sidebarShellState = {
  evaluatedAt: '2026-09-07T12:00:00Z',
  header: {
    appName: 'INSPR',
    instanceLabel: 'Paimos dev',
    version: 'shell-0.1.2',
    userInitials: 'MK',
    userLabel: 'Markus',
    projectName: 'Northstar booking experience refresh',
    projectSubtitle: 'Mobile-first delivery batch',
  },
  health: {
    status: 'available',
    label: 'Live product available',
    checkedLabel: 'Host checked 2 min ago',
    url: 'https://example.test/health',
  },
  delivery: {
    liveReleaseLabel: 'Live product',
    batchTitle: 'Make booking effortless',
    batchSummary: '2 changes · selected delivery batch',
    draftCount: 2,
    mapDetail:
      'Aithema baseline confirmed. Paimos build waits for your explicit start. Pharos deliver and Janus access stay gated on their own evidence.',
    batchRef: 'batch_northstar_1',
    baselineRef: 'baseline_7',
    baselineDigest: 'sha256:dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
    status: 'draft',
    activeStage: 0,
    stageEvidence: ['performed', 'unknown', 'unknown', 'unknown'],
    batchStatusLabel: 'Ready to begin',
    scopeItems: ['Simplify the booking form', 'Add a clear confirmation'],
  },
  prerequisites: {
    requirementsBaseline: {
      status: 'pass',
      message: 'Requirements baseline confirmed for this batch.',
      gateKind: 'requirements_baseline',
      evidenceRef: 'evidence_req_northstar',
      observedAt: '2026-09-07T11:55:00Z',
      freshUntil: '2026-09-07T12:10:00Z',
    },
    deployArtifact: {
      status: 'unknown',
      message: 'Deployable preview artifact not reported yet.',
      gateKind: 'artifact',
      evidenceRef: null,
      observedAt: null,
    },
    pharosTarget: {
      status: 'pass',
      readiness: 'preliminary',
      message: 'Preliminary Pharos target supports Janus preparation only.',
      gateKind: 'target_readiness',
      evidenceRef: 'evidence_pharos_northstar',
      observedAt: '2026-09-07T11:55:00Z',
      targetRef: 'target_prod_northstar',
    },
    janusGate: {
      status: 'unknown',
      message: 'Janus access application requires ready or live target evidence.',
      gateKind: 'access',
      evidenceRef: null,
      observedAt: null,
    },
  },
  progress: {
    taskLabel: 'Requirements ready',
    overallLabel: 'Overall',
    task: {
      progress: {
        status: 'done',
        percent_complete: 100,
        eta: null,
        basis: { kind: 'observed_work', evidence_ref: 'evidence_req_northstar' },
        reporter: { kind: 'human', reporter_ref: 'party_customer' },
        reported_at: '2026-09-07T11:55:00Z',
        fresh_until: '2026-09-07T12:10:00Z',
        freshness: 'fresh',
      },
      forecast: null,
    },
    overall: {
      progress: {
        status: 'in_progress',
        percent_complete: 18,
        eta: null,
        basis: { kind: 'work_breakdown', evidence_ref: 'evidence_overall' },
        reporter: { kind: 'system', reporter_ref: 'reporter_host' },
        reported_at: '2026-09-07T12:00:00Z',
        fresh_until: '2026-09-07T12:10:00Z',
        freshness: 'fresh',
      },
      forecast: {
        percent_complete: 18,
        estimated_finish: '2026-09-07T12:50:00Z',
        kind: 'educated_guess',
        as_of: '2026-09-07T12:00:00Z',
        basis: { kind: 'elapsed_revision', evidence_ref: 'evidence_overall_forecast' },
      },
    },
  },
  selectedExecutionMode: 'manual',
  selectedAction: 'build',
  identityContext: {
    contract_version: 'inspr.flow-identity/0.1-draft',
    host_id: 'host_fixture_sidebar',
    principal_kind: 'local_host',
    principal_ref: 'host_fixture_sidebar:principal_demo',
    binding_ref: 'host_fixture_sidebar:binding_demo',
    project_ref: 'host_fixture_sidebar:project_northstar',
    context_revision: 'host_fixture_sidebar:ctx_1',
    issued_at: '2026-09-07T11:50:00Z',
    expires_at: '2026-09-07T13:00:00Z',
    display: { fixture_label: 'Labelled sidebar-host fixture' },
  },
};
