export const draftShellState = {
  evaluatedAt: '2026-09-07T12:00:00Z',
  header: {
    appName: 'INSPR',
    instanceLabel: 'Host A',
    version: 'shell-0.1',
    userInitials: 'M',
    userLabel: 'Markus',
    projectName: 'Northstar',
    projectSubtitle: 'Booking experience',
  },
  health: {
    status: 'available',
    label: 'Live product available',
    checkedLabel: 'Host checked 2 min ago',
    url: 'https://example.test/health',
  },
  delivery: {
    liveReleaseLabel: 'Live product',
    batchTitle: 'Make booking effortless',
    batchSummary: '2 changes · selected delivery batch',
    draftCount: 2,
    mapDetail:
      'Aithema baseline confirmed. Paimos build waits for your explicit start. Pharos deliver and Janus access stay gated on their own evidence.',
    batchRef: 'batch_northstar_1',
    baselineRef: 'baseline_7',
    baselineDigest: 'sha256:dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
    status: 'draft',
    activeStage: 0,
    stageEvidence: ['performed', 'unknown', 'unknown', 'unknown'],
    batchStatusLabel: 'Ready to begin',
    scopeItems: ['Simplify the booking form', 'Add a clear confirmation'],
  },
  prerequisites: {
    requirementsBaseline: {
      status: 'pass',
      message: 'Requirements baseline confirmed for this batch.',
      gateKind: 'requirements_baseline',
      evidenceRef: 'evidence_req_northstar',
      observedAt: '2026-09-07T11:55:00Z',
      freshUntil: '2026-09-07T12:10:00Z',
    },
    deployArtifact: {
      status: 'unknown',
      message: 'Deployable preview artifact not reported yet.',
      gateKind: 'artifact',
      evidenceRef: null,
      observedAt: null,
    },
    pharosTarget: {
      status: 'pass',
      readiness: 'preliminary',
      message: 'Preliminary Pharos target supports Janus preparation only.',
      gateKind: 'target_readiness',
      evidenceRef: 'evidence_pharos_northstar',
      observedAt: '2026-09-07T11:55:00Z',
      targetRef: 'target_prod_northstar',
    },
    janusGate: {
      status: 'unknown',
      message: 'Janus access application requires ready or live target evidence.',
      gateKind: 'access',
      evidenceRef: null,
      observedAt: null,
    },
  },
  progress: {
    taskLabel: 'Requirements ready',
    overallLabel: 'Overall',
    task: {
      progress: {
        status: 'done',
        percent_complete: 100,
        eta: null,
        basis: { kind: 'observed_work', evidence_ref: 'evidence_req_northstar' },
        reporter: { kind: 'human', reporter_ref: 'party_customer' },
        reported_at: '2026-09-07T11:55:00Z',
        fresh_until: '2026-09-07T12:10:00Z',
        freshness: 'fresh',
      },
      forecast: {
        percent_complete: 100,
        estimated_finish: '2026-09-07T11:55:00Z',
        kind: 'educated_guess',
        as_of: '2026-09-07T11:55:00Z',
        basis: { kind: 'manual_estimate', evidence_ref: 'evidence_req_forecast' },
        conditional_on: null,
        previous_target: null,
      },
    },
    overall: {
      progress: {
        status: 'pending',
        percent_complete: null,
        eta: null,
        basis: { kind: 'unknown', evidence_ref: null },
        reporter: { kind: 'system', reporter_ref: 'reporter_host_a' },
        reported_at: '2026-09-07T11:55:00Z',
        fresh_until: '2026-09-07T12:10:00Z',
        freshness: 'fresh',
      },
      forecast: {
        percent_complete: 5,
        estimated_finish: '2026-09-07T12:55:00Z',
        kind: 'educated_guess',
        as_of: '2026-09-07T11:55:00Z',
        basis: { kind: 'work_breakdown', evidence_ref: 'evidence_overall_forecast' },
        conditional_on: null,
        previous_target: null,
      },
    },
  },
  executionModes: ['manual', 'assisted', 'automatic'],
  selectedExecutionMode: 'manual',
  selectedAction: 'build',
  identityContext: {
    contract_version: 'inspr.flow-identity/0.1-draft',
    evaluated_at: '2026-09-07T12:00:00Z',
    host_id: 'host_fixture_a',
    principal_kind: 'local_host',
    principal_ref: 'host_fixture_a:principal:labelled-demo',
    binding_ref: 'host_fixture_a:binding:northstar-1',
    organization_ref: null,
    project_ref: 'host_fixture_a:project:northstar',
    actor_kind: 'human',
    issued_at: '2026-09-07T11:55:00Z',
    expires_at: '2026-09-07T20:00:00Z',
    fresh_until: '2026-09-07T12:10:00Z',
    context_revision: 'host_fixture_a:ctxrev:1',
    authority_disclaimer:
      'Schema validity is not authentication. Host must issue this context from a verified principal and revalidate on every consequential intent.',
    display: {
      user_label: 'Labelled fixture person',
      user_initials: 'LF',
      project_label: 'Northstar',
      fixture_label: 'Labelled local-host fixture. No live identity.',
    },
  },
};
