export const runningShellState = {
  evaluatedAt: '2026-09-07T12:14:00Z',
  header: {
    appName: 'INSPR',
    instanceLabel: 'Host B',
    version: 'shell-0.1',
    userInitials: 'A',
    userLabel: 'Alex',
    projectName: 'Harbor',
    projectSubtitle: 'Ops dashboard',
  },
  health: {
    status: 'degraded',
    label: 'Preview host responding slowly',
    checkedLabel: 'Host checked 6 min ago',
    url: 'https://example.test/status',
  },
  delivery: {
    liveReleaseLabel: 'Live dashboard',
    batchTitle: 'Clarify incident banner',
    batchSummary: '1 change · in progress',
    draftCount: 1,
    mapDetail:
      'Paimos build produced a preview artifact. Pharos deliver is in progress; Janus access stays gated until the target is ready or live.',
    batchRef: 'batch_harbor_3',
    baselineRef: 'baseline_12',
    baselineDigest: 'sha256:eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
    status: 'in_progress',
    activeStage: 2,
    stageEvidence: ['performed', 'performed', 'unknown', 'unknown'],
    batchStatusLabel: 'Update overdue',
    scopeItems: ['Clarify incident banner copy'],
  },
  prerequisites: {
    requirementsBaseline: {
      status: 'pass',
      message: 'Baseline locked for batch_harbor_3.',
      gateKind: 'requirements_baseline',
      evidenceRef: 'evidence_req_harbor',
      observedAt: '2026-09-07T11:40:00Z',
      freshUntil: '2026-09-07T12:00:00Z',
    },
    deployArtifact: {
      status: 'pass',
      message: 'Preview artifact recorded.',
      gateKind: 'artifact',
      evidenceRef: 'artifact_harbor_preview',
      observedAt: '2026-09-07T11:50:00Z',
      digest: 'sha256:ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
    },
    pharosTarget: {
      status: 'pass',
      readiness: 'ready',
      message: 'Pharos target ready for preview delivery.',
      gateKind: 'target_readiness',
      evidenceRef: 'evidence_pharos_harbor',
      observedAt: '2026-09-07T11:50:00Z',
      targetRef: 'target_harbor_preview',
    },
    janusGate: {
      status: 'unknown',
      message: 'Access application waits on completed delivery evidence.',
      gateKind: 'access',
      evidenceRef: null,
      observedAt: null,
    },
  },
  progress: {
    taskLabel: 'Testing preview flow',
    overallLabel: 'Overall',
    task: {
      progress: {
        status: 'in_progress',
        percent_complete: 60,
        eta: null,
        basis: { kind: 'task_assessment', evidence_ref: 'evidence_try_3' },
        reporter: { kind: 'worker', reporter_ref: 'worker_harbor' },
        reported_at: '2026-09-07T12:00:00Z',
        fresh_until: '2026-09-07T12:05:00Z',
        freshness: 'fresh',
      },
      forecast: {
        percent_complete: 62,
        estimated_finish: '2026-09-07T12:35:00Z',
        kind: 'worker_estimate',
        as_of: '2026-09-07T12:00:00Z',
        basis: { kind: 'worker_assessment', evidence_ref: 'evidence_try_forecast' },
        conditional_on: null,
        previous_target: null,
      },
    },
    overall: {
      progress: {
        status: 'in_progress',
        percent_complete: 75,
        eta: null,
        basis: { kind: 'work_breakdown', evidence_ref: 'evidence_overall_3' },
        reporter: { kind: 'system', reporter_ref: 'reporter_host_b' },
        reported_at: '2026-09-07T12:00:00Z',
        fresh_until: '2026-09-07T12:05:00Z',
        freshness: 'fresh',
      },
      forecast: {
        percent_complete: 78,
        estimated_finish: '2026-09-07T12:50:00Z',
        kind: 'educated_guess',
        as_of: '2026-09-07T12:00:00Z',
        basis: { kind: 'elapsed_revision', evidence_ref: 'evidence_overall_forecast' },
        conditional_on: null,
        previous_target: {
          percent_complete: 70,
          estimated_finish: '2026-09-07T12:40:00Z',
          as_of: '2026-09-07T11:40:00Z',
          evidence_ref: 'evidence_overall_forecast_prior',
        },
      },
    },
    freshnessLabel: 'Host string still says fresh',
  },
  executionModes: ['manual', 'assisted'],
  selectedExecutionMode: 'assisted',
  selectedAction: 'deploy',
};
